### PR TITLE
Store badge in Wiki

### LINKED ISSUE #7: Storing json in wiki ?
Storing the JSON for shields.io in Gist is really smart, but this requires a few shenanigans.
Do you think it might be possible to store the json in a github wiki file?

### Explanations

You can clone a repo's wiki (`git clone git@github.com:owner/repo.wiki.git`) and push files to it. Files pushed to a wiki are not visible in the repo's UI, but you can fetch them through the URL `https://raw.githubusercontent.com/wiki/:owner/:repo/:file-path`. This seems to work even if wiki is disabled for the project. (usually takes a few minutes for the URL to be updated but for the badges, I'd say it's usually not a problem, shields also does caching anyway)

### Pros

- You don't have to configure a gist. This makes the action much easier to configure
- Also, you don't end up with multiple gists linked to repos around your gist account

### Cons

- You mess with the repo's wiki. Not that much that it might be problematic, I think, but still.
- There's no web UI letting you inspect the json. I don't think it's an important part of the action
- GitHub might change their way of doing. In the future, wiki URLs might become unavailable for repos that have disabled wikis. But it seems to work as of today.

### Unknowns

Will the token provided in GitHub actions be enough to push on the wiki ? We'll have to test that.
It's possible that it still requires a PAT, but no gist. But the scope of the PAT might need to be bigger. Need to test this more.

### Conclusion

If you think this is out of scope for this action, I'll probably try on my own (might be a fork of this action)

### PR DESCRIPTION
**Pull request by ewjoachim**
Fixes #7

(I'll make proper commits, for now I'm just checking if it works)

### CODE REVIEW

**Comment by Schneegans** [comment]
Great to see you working on this!

Could it be possible to use [simple-git](https://www.npmjs.com/package/simple-git) instead of [isomorpic-git](https://www.npmjs.com/package/simple-git) as it seems to have much less dependencies? And I guess that `git` is installed on the runners :smile: Or is this a bad idea for some reason?

**Comment by ewjoachim** [comment]
Ok, I had something that kinda worked locally, and I'm testing it in https://github.com/ewjoachim/test-something/blob/master/.github/workflows/test.yml
It fails: https://github.com/ewjoachim/test-something/runs/3076433742?check_suite_focus=true

1. It fails but the process doesn't end with status 1, not sure why
2. Failure message didn't include the failing line which makes debugging harder

I could spend time trying to get a better understanding, but I'm not sure when I'll have the time to. If you can shine some light on it, that might speed up the process quite a bit :)
(I'm a Python dev, haven't spent that much time playing with Node)

What would be left, IMO:
- [ ] Fix what's broken
- [ ] Better error-handling, better error messages
- [ ] In both cases (wiki or gist), somehow print the URL for the badge. This would make usage easier.
- [ ] Documentation

I can try and do a few of those points but I feel I'm not far from the time I would feel comfortable spending given my other commitments :)

**Comment by ewjoachim** [comment]
I just realized that the setup would have made it trivial for you to retrieve the content of my personal access token, so I just revoked it, but I'm guessing you have a test setup on you side.

How do normal people develop github actions ?

**Comment by ewjoachim** [comment]
(since then, I published https://github.com/ewjoachim/coverage-comment-action )

**Pull request closed without merging**
